"""Project orientation: deterministic facts + provenance, zero-daemon.

A thin SYNTHESIS layer over existing capabilities (git, config files,
filesystem, lightweight AST patterns). It is not an AST engine, not a
search engine, not a scope resolver, not an evidence engine.

Output schema (stable, schema=1):

    {schema, cache_key, repo, stack, layout, tooling,
     entry_points, hotspots, generated_candidates, warnings}

Every detected fact carries provenance:
    {"value": ..., "source": ..., "confidence": ...}
confidence is one of: direct | detected | inferred  (never fabricated;
fact() rejects anything else).

Modes:
    --quick      git state, stack, layout, tooling, config locations
    --standard   + entry points, hotspots, generated candidates, warnings
    --deep       + schema/model candidates and public symbol inventory

Cache: external state cache/orient.json keyed per mode by tree_hash (clean tree
only). A dirty working tree bypasses the persistent cache entirely --
stale orientation is never served.
"""

from __future__ import annotations

import sys

if __package__ in (None, ""):
    # Direct-script mode: drop this directory from sys.path BEFORE any
    # stdlib import -- the sibling types.py would otherwise shadow stdlib
    # `types` and kill the import chain on GenericAlias (same guard as
    # asha/__main__.py and asha/mcp_server.py).
    def _asha_norm(entry: str) -> str:
        return (entry or ".").replace(chr(92), "/").rstrip("/").lower()

    _asha_pkg = _asha_norm(__file__).rsplit("/", 1)[0]
    sys.path = [entry for entry in sys.path if _asha_norm(entry) != _asha_pkg]
    sys.path.insert(0, _asha_pkg.rsplit("/", 1)[0])

import argparse
import ast
import json
import os
import re
import subprocess
import tempfile
from pathlib import Path

from .common import paths as common_paths

try:
    from . import scope_resolver  # reuse: _DYNAMIC_RE marker set + PYTHON_SKIP_DIRS
except ImportError:  # direct-script mode (repo root on sys.path)
    from asha import scope_resolver  # reuse: _DYNAMIC_RE marker set + PYTHON_SKIP_DIRS

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    tomllib = None  # type: ignore[assignment]

SCHEMA = 1
CACHE_REL = None  # replaced by common_paths.get_cache_dir(root) / 'orient.json'
CONFIDENCES = ('direct', 'detected', 'inferred')
MARKER_RE = re.compile(
    r'code generated|do not edit|@generated|autogenerated|'
    r'automatically generated', re.IGNORECASE)
GENERATED_NAME_RE = re.compile(
    r'_pb2(_grpc)?\.py$|\.generated\.[^.]+$|next-env\.d\.ts$|'
    r'\.g\.dart$|_gen\.py$')
KNOWN_FRAMEWORKS = {
    'python': ('fastapi', 'flask', 'django', 'litestar', 'tornado', 'aiohttp'),
    'javascript': ('react', 'next', 'vue', 'express', 'svelte', 'nestjs'),
}
ENTRY_KINDS = ('FastAPI', 'Flask', 'Typer', 'click')
SCHEMA_BASES = ('BaseModel', 'TypedDict', 'NamedTuple', 'Document')
MAX_SCAN_FILES = 500
MAX_TRACKED_HEAD_READ = 2000
MAX_ENTRIES = 100


class OrientError(Exception):
    pass


def fact(value, source: str, confidence: str) -> dict:
    if confidence not in CONFIDENCES:
        raise ValueError('fabricated confidence: ' + repr(confidence))
    return {'value': value, 'source': source, 'confidence': confidence}


def path_fact(path: str, source: str, confidence: str) -> dict:
    if confidence not in CONFIDENCES:
        raise ValueError('fabricated confidence: ' + repr(confidence))
    return {'path': path, 'source': source, 'confidence': confidence}


def _git(root: Path, *args: str) -> str:
    proc = subprocess.run(['git', *args], cwd=root, capture_output=True,
                          text=True, timeout=60)
    if proc.returncode != 0:
        raise OrientError('git ' + ' '.join(args) + ': '
                          + proc.stderr.strip())
    return proc.stdout


def repo_facts(root: Path) -> dict:
    commit = _git(root, 'rev-parse', 'HEAD').strip()
    tree_hash = _git(root, 'rev-parse', 'HEAD^{tree}').strip()
    branch = _git(root, 'rev-parse', '--abbrev-ref', 'HEAD').strip()
    porcelain = subprocess.run(['git', 'status', '--porcelain'], cwd=root,
                               capture_output=True, text=True, timeout=60)
    if porcelain.returncode != 0:
        raise OrientError('git status failed: ' + porcelain.stderr.strip())
    dirty = bool(porcelain.stdout.strip())
    return {'tree_hash': tree_hash, 'commit': commit, 'branch': branch,
            'is_dirty': dirty}


def _read_toml(root: Path) -> dict:
    path = root / 'pyproject.toml'
    if not path.is_file() or tomllib is None:
        return {}
    try:
        with path.open('rb') as handle:
            return tomllib.load(handle)
    except (OSError, ValueError):
        return {}


def _deps_of(config: dict, package_json: dict) -> list[str]:
    names: list[str] = []
    project = config.get('project', {})
    names += [str(d).split()[0].split('>')[0].split('=')[0].lower()
              for d in project.get('dependencies', []) if isinstance(d, str)]
    poetry = config.get('tool', {}).get('poetry', {})
    names += [str(k).lower() for k in poetry.get('dependencies', {})]
    names += [str(k).lower()
              for group in config.get('dependency-groups', {}).values()
              for k in group]
    names += [str(k).lower() for k in package_json.get('dependencies', {})]
    names += [str(k).lower() for k in package_json.get('devDependencies', {})]
    return names


def stack_facts(root: Path, tracked_py: list[str]) -> dict:
    config = _read_toml(root)
    pkg_path = root / 'package.json'
    package_json: dict = {}
    if pkg_path.is_file():
        try:
            package_json = json.loads(pkg_path.read_text(encoding='utf-8'))
        except (OSError, ValueError):
            package_json = {}

    if (root / 'pyproject.toml').is_file() or (root / 'setup.py').is_file():
        language = fact('python', 'pyproject.toml', 'direct')
    elif package_json:
        language = fact('javascript', 'package.json', 'direct')
    elif tracked_py:
        language = fact('python', 'filesystem', 'detected')
    else:
        language = None

    deps = _deps_of(config, package_json)
    known = KNOWN_FRAMEWORKS.get(
        language['value'] if language else '', ())
    framework = None
    for name in known:
        if name in deps:
            source = 'pyproject.toml' if config else 'package.json'
            framework = fact(name, source, 'direct')
            break

    build_system = None
    tool = config.get('tool', {})
    if 'poetry' in tool or (root / 'poetry.lock').is_file():
        build_system = fact('poetry', 'pyproject.toml', 'direct')
    elif (root / 'uv.lock').is_file():
        build_system = fact('uv', 'uv.lock', 'direct')
    elif 'hatch' in tool:
        build_system = fact('hatch', 'pyproject.toml', 'direct')
    elif 'setuptools' in tool or (root / 'setup.py').is_file():
        build_system = fact('setuptools', 'pyproject.toml', 'direct')

    return {'language': language, 'framework': framework,
            'build_system': build_system}


def _py_dirs(root: Path) -> list[Path]:
    found: list[Path] = []
    for path in root.rglob('*.py'):
        rel_parts = path.relative_to(root).parts
        if any(part in scope_resolver.PYTHON_SKIP_DIRS for part in rel_parts):
            continue
        found.append(path.parent)
    return found


def layout_facts(root: Path) -> dict:
    top: list[Path] = []
    for entry in sorted(root.iterdir()):
        name = entry.name
        if name in ('.git',) or name in scope_resolver.PYTHON_SKIP_DIRS:
            continue
        if entry.is_dir():
            top.append(entry)

    test_dirs: set[str] = set()
    package_dirs: set[str] = set()
    source_dirs: set[str] = set()
    for parent in _py_dirs(root):
        rel = parent.relative_to(root).as_posix()
        names = {p.name for p in parent.glob('*.py')}
        if parent.joinpath('__init__.py').exists():
            package_dirs.add(rel)
        if any(n.startswith('test_') for n in names) or \
                parent.name in ('tests', 'test'):
            test_dirs.add(rel)
        else:
            source_dirs.add(rel)

    important = [path_fact(p.relative_to(root).as_posix(),
                           'filesystem', 'detected') for p in top]
    return {
        'project_name': fact(root.name, 'filesystem', 'detected'),
        'source_roots': [path_fact(d, 'filesystem', 'detected')
                         for d in sorted(source_dirs - test_dirs)],
        'test_roots': [path_fact(d, 'filesystem', 'detected')
                       for d in sorted(test_dirs)],
        'package_roots': [path_fact(d, 'filesystem', 'detected')
                          for d in sorted(package_dirs)],
        'important_dirs': important,
    }


def tooling_facts(root: Path) -> dict:
    config_names = ('ruff.toml', '.ruff.toml', 'mypy.ini', '.mypy.ini',
                    'pytest.ini', 'pyproject.toml', 'setup.cfg', 'tox.ini',
                    'package.json', 'tsconfig.json', '.pre-commit-config.yaml')
    config_files = [path_fact(name, 'filesystem', 'detected')
                    for name in config_names if (root / name).is_file()]
    config = _read_toml(root)
    tool = config.get('tool', {})

    if (root / 'ruff.toml').is_file():
        lint = fact('ruff', 'ruff.toml', 'direct')
    elif (root / '.ruff.toml').is_file():
        lint = fact('ruff', '.ruff.toml', 'direct')
    elif 'ruff' in tool:
        lint = fact('ruff', 'pyproject.toml', 'direct')
    else:
        lint = None
    if (root / 'mypy.ini').is_file():
        type_checker = fact('mypy', 'mypy.ini', 'direct')
    elif (root / '.mypy.ini').is_file():
        type_checker = fact('mypy', '.mypy.ini', 'direct')
    elif 'mypy' in tool:
        type_checker = fact('mypy', 'pyproject.toml', 'direct')
    else:
        type_checker = None
    if (root / 'pytest.ini').is_file():
        test_runner = fact('pytest', 'pytest.ini', 'direct')
    elif 'pytest' in tool:
        test_runner = fact('pytest', 'pyproject.toml', 'direct')
    else:
        test_runner = None

    venv = root / '.hermes' / 'venv'
    if venv.is_dir():
        bins = venv / ('Scripts' if os.name == 'nt' else 'bin')
        names = {p.stem.lower() for p in bins.glob('*')} if bins.is_dir() else set()
        if lint is None and 'ruff' in names:
            lint = fact('ruff', '.hermes/venv', 'detected')
        if type_checker is None and 'mypy' in names:
            type_checker = fact('mypy', '.hermes/venv', 'detected')
        if test_runner is None and 'pytest' in names:
            test_runner = fact('pytest', '.hermes/venv', 'detected')

    return {'test_runner': test_runner, 'lint': lint,
            'type_checker': type_checker, 'config_files': config_files}


def _iter_py(root: Path, limit: int = MAX_SCAN_FILES):
    count = 0
    for path in sorted(root.rglob('*.py')):
        rel_parts = path.relative_to(root).parts
        if any(part in scope_resolver.PYTHON_SKIP_DIRS for part in rel_parts):
            continue
        if count >= limit:
            break
        count += 1
        yield path


def entry_points(root: Path, deep: bool = False) -> list[dict]:
    entries: list[dict] = []
    config = _read_toml(root)
    for name, target in (config.get('project', {}).get('scripts', {}) or
                         {}).items():
        entries.append({'kind': 'console_script', 'value':
                        f'{name} = {target}', 'source': 'pyproject.toml',
                        'confidence': 'direct'})
    poetry_scripts = config.get('tool', {}).get('poetry', {}).get('scripts', {}) or {}
    for name, target in poetry_scripts.items():
        entries.append({'kind': 'console_script', 'value':
                        f'{name} = {target}', 'source': 'pyproject.toml',
                        'confidence': 'direct'})
    pkg_path = root / 'package.json'
    if pkg_path.is_file():
        try:
            package_json = json.loads(pkg_path.read_text(encoding='utf-8'))
        except (OSError, ValueError):
            package_json = {}
        for key in ('main', 'bin'):
            if key in package_json:
                entries.append({'kind': f'package_{key}',
                                'value': str(package_json[key]),
                                'source': 'package.json',
                                'confidence': 'direct'})

    for path in _iter_py(root):
        rel = path.relative_to(root).as_posix()
        try:
            tree = ast.parse(path.read_text(encoding='utf-8'))
        except (OSError, UnicodeDecodeError, SyntaxError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.If):
                test = ast.dump(node.test)
                if '__main__' in test:
                    entries.append({'kind': 'cli_main', 'path': rel,
                                    'line': node.lineno, 'source': rel,
                                    'confidence': 'detected'})
            elif isinstance(node, ast.Assign):
                calls = [t for t in node.targets if isinstance(t, ast.Name)]
                if isinstance(node.value, ast.Call):
                    func = node.value.func
                    fname = (func.id if isinstance(func, ast.Name)
                             else func.attr if isinstance(func, ast.Attribute)
                             else '')
                    if fname in ENTRY_KINDS and calls:
                        entries.append({'kind': fname.lower() + '_app',
                                        'path': rel, 'line': node.lineno,
                                        'value': calls[0].id, 'source': rel,
                                        'confidence': 'detected'})
        if deep:
            publics = [n.name for n in tree.body
                       if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef,
                                         ast.ClassDef))
                       and not n.name.startswith('_')]
            if publics:
                entries.append({'kind': 'public_symbols', 'path': rel,
                                'value': sorted(publics), 'source': rel,
                                'confidence': 'detected'})
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    bases = [ast.unparse(b).split('.')[-1] for b in node.bases]
                    decorator = any('dataclass' in ast.unparse(d)
                                    for d in node.decorator_list)
                    if any(b in SCHEMA_BASES for b in bases) or decorator:
                        entries.append({'kind': 'schema_model', 'path': rel,
                                        'line': node.lineno,
                                        'value': node.name, 'source': rel,
                                        'confidence': 'detected'})
    return entries[:MAX_ENTRIES]


def hotspot_facts(root: Path) -> list[dict]:
    records = _git(root, 'log', '-n', '50',
                   '--format=%H%x00%ae%x00%aI%x00%s').strip()
    entries: list[dict] = []
    authors: list[str] = []
    last = None
    if records:
        rows = [line.split('\x00') for line in records.splitlines()
                if line.strip()]
        authors = sorted({row[1] for row in rows if len(row) >= 2})
        first = rows[0]
        if len(first) >= 4:
            last = {'commit': first[0], 'author': first[1],
                    'authored_at': first[2], 'subject': first[3]}
    entries.append({'signal': 'revisions_seen', 'value': len(rows),
                    'window': 'git log -n 50', 'source': 'git log',
                    'confidence': 'detected'})
    entries.append({'signal': 'unique_authors', 'value': len(authors),
                    'authors': authors, 'source': 'git log',
                    'confidence': 'detected'})
    if last:
        entries.append({'signal': 'last_change', 'value': last,
                        'source': 'git log', 'confidence': 'direct'})
    names = _git(root, 'log', '-n', '50', '--name-only', '--format=')
    counts: dict[str, int] = {}
    for line in names.splitlines():
        line = line.strip()
        if line:
            counts[line] = counts.get(line, 0) + 1
    top = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))[:10]
    entries.append({'signal': 'most_touched_recently',
                    'value': [{'path': p, 'touches': c} for p, c in top],
                    'window': 'git log -n 50 --name-only',
                    'source': 'git log', 'confidence': 'detected'})
    return entries


def generated_candidates(root: Path) -> list[dict]:
    proc = subprocess.run(['git', 'ls-files'], cwd=root, capture_output=True,
                          text=True, timeout=60)
    if proc.returncode != 0:
        raise OrientError('git ls-files failed: ' + proc.stderr.strip())
    files = [f for f in proc.stdout.splitlines() if f.strip()]
    out: list[dict] = []
    for rel in files:
        if GENERATED_NAME_RE.search(rel):
            out.append({'path': rel, 'marker': 'filename pattern',
                        'source': 'filename-pattern',
                        'confidence': 'detected'})
            continue
        if len(out) + len(files) and len(out) >= MAX_ENTRIES:
            break
        if not rel.endswith(('.py', '.ts', '.js', '.tsx', '.jsx', '.json',
                             '.yml', '.yaml', '.md', '.txt', '.toml', '.cfg')):
            continue
        if rel.count('/') > 6:
            continue
        path = root / rel
        if not path.is_file():
            continue
        try:
            head = ''.join(path.read_text(encoding='utf-8',
                                          errors='replace').splitlines(True)[:5])
        except OSError:
            continue
        match = MARKER_RE.search(head)
        if match:
            out.append({'path': rel, 'marker': match.group(0),
                        'source': 'file-header', 'confidence': 'detected'})
        if len(out) >= MAX_ENTRIES:
            break
    return out


_DYNAMIC_CALLS = {'eval', 'exec', 'globals', 'locals', '__import__'}


def _dynamic_uses(path: Path) -> bool:
    """AST-level detection: only real calls/imports count as facts.

    A text regex would match its own warning label or a docstring -- those
    are not dynamic constructs, so claims stay observable facts.
    """
    try:
        tree = ast.parse(path.read_text(encoding='utf-8'))
    except (OSError, UnicodeDecodeError, SyntaxError):
        return False
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            if any(a.name.split('.')[0] == 'importlib'
                   for a in node.names):
                return True
        elif isinstance(node, ast.ImportFrom):
            if (node.module or '').split('.')[0] == 'importlib':
                return True
        elif isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Name) and func.id in _DYNAMIC_CALLS:
                return True
            if isinstance(func, ast.Attribute) \
                    and func.attr in ('eval', 'exec'):
                return True
    return False


def warnings_facts(root: Path, stack: dict, layout: dict,
                   tooling: dict) -> list[dict]:
    out: list[dict] = []
    dynamic: list[str] = []
    for path in _iter_py(root):
        if _dynamic_uses(path):
            dynamic.append(path.relative_to(root).as_posix())
    if dynamic:
        out.append({'condition': 'dynamic constructs present '
                    '(eval/exec/locals/globals/__import__/importlib)',
                    'source': ', '.join(dynamic[:5]),
                    'confidence': 'detected'})

    config = _read_toml(root)
    tool = config.get('tool', {})
    ruff_configs = [(root / n).is_file() for n in ('ruff.toml', '.ruff.toml')]
    if sum(ruff_configs) + (1 if 'ruff' in tool else 0) > 1:
        out.append({'condition': 'multiple ruff configurations',
                    'source': 'ruff.toml, pyproject.toml',
                    'confidence': 'direct'})
    mypy_configs = [(root / n).is_file() for n in ('mypy.ini', '.mypy.ini')]
    if sum(mypy_configs) + (1 if 'mypy' in tool else 0) > 1:
        out.append({'condition': 'multiple mypy configurations',
                    'source': 'mypy.ini, pyproject.toml',
                    'confidence': 'direct'})

    if not layout['source_roots'] and not stack['language']:
        out.append({'condition': 'unrecognized project layout',
                    'source': 'filesystem', 'confidence': 'detected'})

    repo_branch = _git(root, 'rev-parse', '--abbrev-ref', 'HEAD').strip()
    if repo_branch == 'HEAD':
        out.append({'condition': 'detached HEAD', 'source': 'git',
                    'confidence': 'direct'})
    return out


# ---- cache ---------------------------------------------------------------

def _cache_path(root: Path) -> Path:
    return common_paths.get_cache_dir(root) / 'orient.json'


def _cache_load(root: Path) -> dict:
    path = _cache_path(root)
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding='utf-8'))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _cache_store(root: Path, mode: str, tree_hash: str, result: dict) -> None:
    path = _cache_path(root)
    path.parent.mkdir(parents=True, exist_ok=True)
    data = _cache_load(root)
    raw = data.get('entries')
    entries = raw if isinstance(raw, dict) else {}
    entries[mode] = {'cache_key': tree_hash, 'result': result}
    payload = json.dumps({'schema': SCHEMA, 'entries': entries},
                         sort_keys=True, indent=2).encode('utf-8')
    fd, tmp = tempfile.mkstemp(prefix='.orient-', dir=path.parent)
    try:
        with os.fdopen(fd, 'wb') as handle:
            handle.write(payload)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp, path)
    finally:
        if os.path.exists(tmp):
            os.unlink(tmp)


# ---- build ---------------------------------------------------------------

def build(root: Path | str, mode: str = 'standard',
          use_cache: bool = True) -> dict:
    root = Path(root).resolve()
    if mode not in ('quick', 'standard', 'deep'):
        raise OrientError('unknown mode: ' + repr(mode))
    repo = repo_facts(root)
    cache_key = None if repo['is_dirty'] else repo['tree_hash']

    if use_cache and cache_key is not None:
        stored = _cache_load(root).get('entries', {}).get(mode)
        if isinstance(stored, dict) and stored.get('cache_key') == cache_key:
            cached = stored.get('result')
            if isinstance(cached, dict) and cached.get('schema') == SCHEMA:
                return cached

    tracked_py = [p for p in subprocess.run(
        ['git', 'ls-files', '*.py'], cwd=root, capture_output=True,
        text=True, timeout=60).stdout.splitlines() if p]
    stack = stack_facts(root, tracked_py)
    layout = layout_facts(root)
    tooling = tooling_facts(root)
    result: dict = {'schema': SCHEMA, 'cache_key': cache_key, 'repo': repo,
                    'stack': stack, 'layout': layout, 'tooling': tooling,
                    'entry_points': [], 'hotspots': [],
                    'generated_candidates': [], 'warnings': []}
    if mode in ('standard', 'deep'):
        result['entry_points'] = entry_points(root, deep=(mode == 'deep'))
        result['hotspots'] = hotspot_facts(root)
        result['generated_candidates'] = generated_candidates(root)
        result['warnings'] = warnings_facts(root, stack, layout, tooling)

    if use_cache and cache_key is not None:
        _cache_store(root, mode, cache_key, result)
    return result


def _show(f) -> str:
    if f is None:
        return 'not detected'
    if isinstance(f, dict) and 'value' in f:
        return str(f['value'])
    return str(f)


def render_markdown(result: dict) -> str:
    stack = result['stack']
    tooling = result['tooling']
    layout = result['layout']

    def roots(key: str) -> list[str]:
        return [f['path'] for f in layout.get(key, [])]

    src_lines = [f'  {p}' for p in roots('source_roots')] or ['  (none)']
    test_lines = [f'  {p}' for p in roots('test_roots')] or ['  (none)']
    entry_lines = [
        f'  [{e.get("kind")}] {e.get("value") or e.get("path")}'
        f'{":" + str(e.get("line")) if e.get("line") else ""}'
        for e in result['entry_points']] or ['  (none detected)']
    lines = [
        'Project: ' + _show(layout.get('project_name')),
        'Language: ' + _show(stack['language']),
        'Framework: ' + _show(stack['framework']),
        'Tests: ' + _show(tooling['test_runner']),
        'Lint: ' + _show(tooling['lint']),
        'Type checking: ' + _show(tooling['type_checker']),
        '',
        'Source roots:',
        *src_lines,
        '',
        'Test roots:',
        *test_lines,
        '',
        'Entry points:',
        *entry_lines,
        '',
        'Recent hotspots:',
    ]
    for signal in result['hotspots']:
        value = signal['value']
        if signal['signal'] == 'last_change':
            value = (f'{value["commit"][:10]} {value["subject"]!r} '
                     f'by {value["author"]} at {value["authored_at"]}')
        elif signal['signal'] == 'most_touched_recently':
            value = ', '.join(f'{i["path"]}({i["touches"]})' for i in value)
        elif signal['signal'] == 'unique_authors':
            value = f'{value}: ' + ', '.join(signal.get('authors', []))
        lines.append(f'  {signal["signal"]}: {value}')
    if not result['hotspots']:
        lines.append('  (none)')
    generated_lines = [
        f'  {c["path"]} ({c["marker"]})'
        for c in result['generated_candidates']] or ['  (none)']
    warning_lines = [
        f'  {w["condition"]} [source: {w["source"]}]'
        for w in result['warnings']] or ['  (none)']
    lines += [
        '',
        'Generated candidates:',
        *generated_lines,
        '',
        'Warnings:',
        *warning_lines,
    ]
    return '\n'.join(lines) + '\n'


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--quick', action='store_true')
    parser.add_argument('--standard', action='store_true')
    parser.add_argument('--deep', action='store_true')
    parser.add_argument('--format', dest='fmt', default='json',
                        choices=['json', 'markdown'])
    parser.add_argument('--root', default='.')
    parser.add_argument('--no-cache', action='store_true')
    args = parser.parse_args(argv)
    mode = ('deep' if args.deep else 'quick' if args.quick else 'standard')
    try:
        result = build(args.root, mode, use_cache=not args.no_cache)
    except (OrientError, ValueError) as exc:
        print('ORIENT ERROR: ' + str(exc), file=sys.stderr)
        return 1
    if args.fmt == 'markdown':
        sys.stdout.write(render_markdown(result))
    else:
        print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == '__main__':
    sys.exit(main())
